import 'package:flutter/material.dart';
import 'package:flutter/widgets.dart';

class Constants {
  static final List<Image> kitoblar = [
    Image.asset("assets/books/BaxtiyorOila.jpg"),
    Image.asset("assets/books/qalqoni.jpg"),
    Image.asset("assets/books/muminningUmrSafari.jpg"),
    Image.asset("assets/books/Qarz.jpg"),
    Image.asset("assets/books/yolgon.jpg"),
    Image.asset("assets/books/Hadis.jpg"),
    Image.asset("assets/books/muminningMeroji.jpg"),
    Image.asset("assets/books/IjtimoiyOdoblar.jpg"),
    Image.asset("assets/books/aqoidIlmi.jpg"),
    Image.asset("assets/books/Amallar.jpg"),
    Image.asset("assets/books/iymon.jpg"),
    Image.asset("assets/books/Ruhiy.jpg"),
    Image.asset("assets/books/Hadis.jpg"),
    Image.asset("assets/books/Hadis21.jpg"),
    Image.asset("assets/books/Soglom.jpg"),
    Image.asset("assets/books/quron.jpg"),
    Image.asset("assets/books/folbinlik.jpg"),
    Image.asset("assets/books/Ruhiy.jpg"),
    Image.asset("assets/books/sofTabiat.jpg"),
    Image.asset("assets/books/Hadis21.jpg"),
    Image.asset("assets/books/mazhablar.jpg"),
    Image.asset("assets/books/Hadis.jpg"),
    Image.asset("assets/books/oltin.jpg"),
    Image.asset("assets/books/Hadis21.jpg"),
    Image.asset("assets/books/Hadis.jpg"),
    Image.asset("assets/books/Odoblar.jpg"),
    Image.asset("assets/books/mukammal.jpg"),
  ];

  static final List<Image> bizningDasturlarImage = [
    Image.asset("assets/image/hilolEbook.webp"),
    Image.asset("assets/image/tafsiriHilol.webp"),
    Image.asset("assets/image/oltinSilsila.webp"),
    Image.asset("assets/image/olimBola.webp"),
    Image.asset("assets/image/namoz.webp"),
    Image.asset("assets/image/zikraxlidansorang.webp"),
    Image.asset("assets/image/zikrDuo.webp"),
    Image.asset("assets/image/hilolTest.webp"),
    Image.asset("assets/image/quronKarim.webp"),
    Image.asset("assets/image/riyozusSolixiyn.webp"),
    Image.asset("assets/image/multfilmlar.webp"),
    Image.asset("assets/image/asmaulXusna.webp"),
    Image.asset("assets/image/zukkoBolajon.webp"),
    Image.asset("assets/image/abduraxmonQuron.webp"),
    Image.asset("assets/image/abdulmalikQuron.webp"),
    Image.asset("assets/image/etiqodDurdonalari.webp"),
    Image.asset("assets/image/quronTartili.webp"),
    Image.asset("assets/image/xikmatlar.webp"),
  ];

  static final List<String> bizningDasturlarName = [
    "Hilol eBook",
    "Tafsiri Hilol",
    "Олтин силсила",
    "Olim Bola",
    "Намоз",
    "Зикр аҳлидан сўранг",
    "Зикр ва дуолар (аудиоси билан)",
    "Hilol Test",
    "Қуръони Карим (сўзма-сўз)",
    "Риёзус солиҳийн",
    "Multfilmlar",
    "Asmaul husna",
    "Zukko Bolajon",
    "Абдураҳмон Қуръон",
    "Абдулмалик Қуръон",
    "Эътиқод дурдоналари",
    "Qur'on tartili",
    "Ҳикматлар"
  ];

  static final List<String> name = [
    "Baxtiyor oila",
    "Mo'minning qalqoni -\nmufassal ro'za kitobi",
    "Mo'minning umr safari -\nmufassal haj kitobi",
    "Qarz",
    "Yolg'on",
    "Hadis va hayot 25-juz.\nNubuvvat xonadoni ...",
    "Mo'minning me'roji",
    "Ijtimoiy odoblar",
    "Aqoid ilmlari",
    "Amallar niyatga bo'g'liqdir",
    "Iymon",
    "Ruhiy tarbiya 1-juz",
    "Hadis va hayot 23-juz.\nJannat bashorati ...",
    "Hadis va hayot 1-juz.\nMuqaddima",
    "Sog'lom bola",
    "Qur'on ilmlari",
    "Folbinlik,sehrgarlik...",
    "Ruhiy tarbiya 2-juz",
    "Sof tabiat dini",
    "Hadis va hayot 20-juz.\nAnbiyolar qissasi",
    "Mazhablar - birlik ramzi",
    "Hadis va hayot 14-juz.\nQasamlar,nazrlar va ov",
    "Oltin silsila. 1-juz",
    "Hadis va hayot 36-juz.\nZuhd va raqoiqlar",
    "Hadis va hayot 28-juz.\nTafsir kitobi",
    "Odoblar hazinasi. 1-juz",
    "Mukammal saodat yo'li"
  ];
}
